name: Black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Setup Python
         uses: actions/setup-python@v2
         with: 
           python-version: 3.9
       - name: Install Black
         run: pip install black
       - name: Run black check
         run: black --check .
       - name: Commit changes if needed
         if: failure()
         run: |
           black .
           git config -global user.name 'autoblack'
           git config -global user.email 'mitch-karch@users.noreply.github.com'
           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
           git checkout $GITHUB_HEAD_REF
           git commit -am "fixup: Format Python code with Black"
           git push